// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwAHY7vfh9R8_gkaIlgBmlxTZGYShDNMw',
    appId: '1:1073876168941:web:38555c232c9a104a2e5ce4',
    messagingSenderId: '1073876168941',
    projectId: 'mood-store-3f4f7',
    authDomain: 'mood-store-3f4f7.firebaseapp.com',
    storageBucket: 'mood-store-3f4f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByGuysfASBtxXi68uYLmuvsXSydQqRlfY',
    appId: '1:1073876168941:android:05d031eb8df88c7b2e5ce4',
    messagingSenderId: '1073876168941',
    projectId: 'mood-store-3f4f7',
    storageBucket: 'mood-store-3f4f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQV8jtxWm0kDZ9AyCWPffVsqV-KwRrsKU',
    appId: '1:1073876168941:ios:18c0ef98a868a2732e5ce4',
    messagingSenderId: '1073876168941',
    projectId: 'mood-store-3f4f7',
    storageBucket: 'mood-store-3f4f7.firebasestorage.app',
    iosBundleId: 'com.example.mood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQV8jtxWm0kDZ9AyCWPffVsqV-KwRrsKU',
    appId: '1:1073876168941:ios:18c0ef98a868a2732e5ce4',
    messagingSenderId: '1073876168941',
    projectId: 'mood-store-3f4f7',
    storageBucket: 'mood-store-3f4f7.firebasestorage.app',
    iosBundleId: 'com.example.mood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwAHY7vfh9R8_gkaIlgBmlxTZGYShDNMw',
    appId: '1:1073876168941:web:9d0f7683a8b5e3052e5ce4',
    messagingSenderId: '1073876168941',
    projectId: 'mood-store-3f4f7',
    authDomain: 'mood-store-3f4f7.firebaseapp.com',
    storageBucket: 'mood-store-3f4f7.firebasestorage.app',
  );
}
